logging:
  config: classpath:log4j2.xml

dubbo:
  application:
    name: zim-server
    logger: log4j2
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
    serialization: protostuff

im:
  port: 10099
  readerIdleTime: 10000
  writerIdleTime: 0
  allIdleTime: 0
