logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zh?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db-config.xml

