logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zh?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
#    host: localhost
#    port: 6379
#    password: 1234qwer
    database: 0
    lettuce:
      pool:
        max-active: 50
        max-wait: 10s
        min-idle: 10
        max-idle: 20

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis:
  config-location: classpath:mybatis-config.xml


